before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap --platform ios
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
script:
  - set -o pipefail
  - xcodebuild test -scheme RxExtensions -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' | xcpretty -c
